### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#866]
The releases should be signed + have a checksum to verify their integrity.

However this supposes to have our own building machines + a way to reproduce them on our own environement, so any allowed developer of Duniter organization could make a build.

Maybe we could use Vagrant or something to build the environement, then building scripts.

**Comment by c-geek** [comment]
I plan to create a `.dunisig` file in YAML format with the following content:

```yml
Version: 1
Hashes:
- Hash: fdeb60589c0f3268d9343d3b4f694808fa71006550a6ba434ed1de2f3b35b1bf
  HashFunc: sha256
  Signatures:
  - Sig: frh6g8G4mk0vMARaS1XtDucMzdRGxvhuNB5sKh+3DhszwYWm0CtczZtncoJleLKthTtQrIOP0wzEFJbzUIiDBA==
    Pub: 4fHMTFBMo5sTQEc5p1CNWz28S4mnnqdUBmECq1zt4n2m
  - Sig: pO4iY5293AnKuyJgw+koW25OwvRmIv47mSR5SYI3UbIbBnPt1oRCcefhvhUbMCyFJb42IYdMNLhIJZExFj4NDA==
    Pub: BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx
- Hash: 0ff4980954ebd750838f5a7e5ae04aa7104a278a
  HashFunc: sha1
  Signatures:
- Hash: eb22e6351ef74084370d50287cf786a3
  HashFunc: md5
  Signatures:
```

This file gives 2 levels of control:

* checksum of the binary, with the different hash given
* authenticity of the hashes, using signatures

The responsibility to say that a given `Pub` is an authority is let to the user. So if, say, YunoHost was checking the binary's hash and the signatures, it may choose to be confident with the checksum only if it was signed by key `A`, or key `A` and key `B`, or 2 `A`, `B` and `C`. Etc.
